#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sat Oct 05 13:40:58 CEST 2024
# SW Build 3671981 on Fri Oct 14 04:59:54 MDT 2022
#
# IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim sim_UART_RX_behav -key {Behavioral:sim_1:Functional:sim_UART_RX} -tclbatch sim_UART_RX.tcl -log simulate.log"
xsim sim_UART_RX_behav -key {Behavioral:sim_1:Functional:sim_UART_RX} -tclbatch sim_UART_RX.tcl -log simulate.log

